### ISSUE TITLE
Use tailwind state selectors instead of child function

### ISSUE THREAD

**Issue by shahyar** [zaichaopan/react-aria-components-tailwind-starter#11]
Hello, great project. Less of an issue and more of a question (there's no discussion section in this repo).

What was the rationale for using child functions to set `className`, rather than the tailwind state selectors? These states are already handled in the Tailwind plugin for react-aria anyways, so one could simply use `unavailable:opacity-50` or `group-unavailable:opacity-50` rather than update the classNames in the DOM.

**Comment by zaichaopan** [comment]
Can you tell me which component you are talking about?  I tried `Tailwind plugin for react-aria` in some components, but does not work. So I ended up using other approaches.  Yea, it will be great to just use react aria tailwind plugin to style. Btw I added `Discussion` in the repo. Thanks for pointing it out.

**Comment by zaichaopan** [comment]
I see what you mean. Yea, using the aria attribute for stying looks better.  Will make the update soon

**Comment by kekswar** [comment]
Also want to thank you, great product!

We also thought about using aria attribute for stying.
For information, there is a nuance - it is necessary to take into account that conditions always exist and are not added conditionally.

Before:

```
disabled:opacity-50
isFocusVisible &&  focus-visible:bg-red-100
```

After:
```
disabled:opacity-50
focus-visible:bg-red-100
```

Now we need to additionally the edge case so that focus doesn't work if the component is disabled.

**Comment by zaichaopan** [comment]
Components are updated using aria or data attributes for stying. Thanks @shahyar for the suggestions
